#!/usr/bin/env bash
# ==============================================================================
# fusionAIze Nexus Labs - Universal Orchestrator & Installer
# Version 0.0.1
# ==============================================================================

set -euo pipefail

# --- Colors & Styling ---
RED='\03.yaml33[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}"
cat << "EOF"
  __           _             _  _______          _   _                     
 / _|         (_)           (_)|__   __|        | \ | |                    
| |_ _   _ ___ _  ___  _ __  _    | | ___  _ __ |_  \| | _____  _   _ ___  
|  _| | | / __| |/ _ \| '_ \| |   | |/ _ \| '_ \  | . ` |/ _ \ \/ / | | / __| 
| | | |_| \__ \ | (_) | | | | |   | | (_) | (_) | | |\  |  __/>  <| |_| \__ \
|_|  \__,_|___/_|\___/|_| |_|_|   |_|\___/ \___/  |_| \_|\___/_/\_\\__,_|___/
                                                                           
                   Nexus Labs Universal Orchestrator                        
EOF
echo -e "${NC}"

# --- Helpers ---
info() { echo -e "${BLUE}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }
prompt() { read -r -p "$(echo -e "${CYAN}$1${NC} ")" "$2"; }

# --- OS Detection ---
OS_TYPE=$(uname -s)
info "Running orchestrator on OS: ${OS_TYPE}"

# --- Output Config ---
TOPOLOGY_FILE=".env.topology"
echo "# Generated by Universal Orchestrator" > "$TOPOLOGY_FILE"

# --- Main Dialog ---
echo ""
echo "Please select the mode of operation:"
echo "  1) Local Installation (Execute directly on this machine)"
echo "  2) Remote Orchestration (Push to another machine via SSH)"
prompt "Enter choice (1/2): " MODE_CHOICE

echo ""
echo "Select the architectural role to provision:"
echo "  1) Edge (Ingress)"
echo "  2) Core (AI Workbench)"
echo "  3) Worker (Local LLM)"
echo "  4) Backup (Synology NAS)"
echo "  5) External (Cloud)"
prompt "Enter role (1-5): " ROLE_CHOICE

ROLE_NAME=""
ROLE_DIR=""

case "$ROLE_CHOICE" in
    1) ROLE_NAME="edge"; ROLE_DIR="edge/pi" ;;
    2) ROLE_NAME="core"; ROLE_DIR="core/heart" ;;
    3) ROLE_NAME="worker"; ROLE_DIR="worker" ;;
    4) ROLE_NAME="backup"; ROLE_DIR="backup" ;;
    5) ROLE_NAME="external"; ROLE_DIR="external" ;;
    *) error "Invalid choice. Exiting." ;;
esac

echo "ROLE=$ROLE_NAME" >> "$TOPOLOGY_FILE"
info "Selected Role: $ROLE_NAME"

# --- Network Config ---
echo ""
prompt "Enter the target Server Hostname [e.g. nexus-core]: " SERVER_NAME
prompt "Enter the target Static IP [e.g. 192.168.178.20]: " TARGET_IP

echo "SERVER_NAME=$SERVER_NAME" >> "$TOPOLOGY_FILE"
echo "TARGET_IP=$TARGET_IP" >> "$TOPOLOGY_FILE"

# --- Core Specifics ---
if [[ "$ROLE_CHOICE" == "2" ]]; then
    echo ""
    prompt "Enable VNC GUI for the AI Workbench? (y/N): " VNC_CHOICE
    if [[ "$VNC_CHOICE" =~ ^[Yy]$ ]]; then
        echo "ENABLE_VNC=true" >> "$TOPOLOGY_FILE"
        info "VNC Server flagged for installation."
    else
        echo "ENABLE_VNC=false" >> "$TOPOLOGY_FILE"
    fi
fi

echo ""
success "Topology configuration saved to $TOPOLOGY_FILE"

# --- Execution Phase ---
if [[ "$MODE_CHOICE" == "1" ]]; then
    info "Initiating Local Installation for $ROLE_NAME..."
    
    if [[ ! -d "$ROLE_DIR" ]]; then
        warning "Directory $ROLE_DIR not found yet, skipping native installation."
    else
        bash "$ROLE_DIR/scripts/install.sh"
    fi
    success "Local setup routine finished."

elif [[ "$MODE_CHOICE" == "2" ]]; then
    echo ""
    prompt "Enter SSH Username for $TARGET_IP: " SSH_USER

    info "Initiating Remote Orchestration to $SSH_USER@$TARGET_IP..."
    
    # 1. Create a remote temp directory
    ssh -t "$SSH_USER@$TARGET_IP" "mkdir -p /tmp/nexus-install"
    
    # 2. SCP payload (the repo) to the target
    info "Transferring payload to target..."
    # We exclude .git and node_modules to make it fast
    rsync -avz --exclude='.git' --exclude='node_modules' ./ "$SSH_USER@$TARGET_IP:/tmp/nexus-install/"
    
    # 3. SCP the topology config
    scp "$TOPOLOGY_FILE" "$SSH_USER@$TARGET_IP:/tmp/nexus-install/"
    
    # 4. Trigger remote script
    info "Executing remote install payload..."
    ssh -t "$SSH_USER@$TARGET_IP" "cd /tmp/nexus-install && bash $ROLE_DIR/scripts/install.sh"
    
    success "Remote deployment complete. (Payload remains in /tmp/nexus-install for debugging)"
else
    error "Invalid mode selected."
fi

echo ""
success "Onboarding Complete."
